FROM golang:1.22-alpine

WORKDIR /app

# Download dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy the source code and build
COPY *.go ./
RUN go build -o main .

# Run the executable
CMD ["./main"]